# Environment
import os

TIME_SPEED_MULTIPLIER = 1000
# Memory
RECENCY_WEIGHT = 1
SIMILARITY_WEIGHT = 1
IMPORTANCE_WEIGHT = 1
REFLECTION_MEMORY_COUNT = 100
PLAN_LENGTH = "24 hours"
DEFAULT_LOCATION_ID = os.getenv("DEFAULT_LOCATION_ID")
DEFAULT_WORLD_ID = os.getenv("DEFAULT_WORLD_ID")
