create extension if not exists "vector" with schema "extensions";


create type "public"."memory_type" as enum ('reflection', 'observation', 'experience');

create table "public"."Agents" (
    "id" bigint generated by default as identity not null,
    "full_name" text,
    "bio" text,
    "directives" text[],
    "pending_plans" bigint[]
);


create table "public"."Memories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "agent_id" bigint,
    "type" memory_type,
    "description" text,
    "related_memories" bigint[],
    "embedding" vector(1536),
    "importance" real,
    "last_accessed" timestamp with time zone,
    "related_agent_ids" bigint[]
);


create table "public"."Plans" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "agent_id" bigint,
    "description" text,
    "max_duration_hrs" smallint,
    "stop_condition" text,
    "completed_at" timestamp with time zone
);


CREATE UNIQUE INDEX "Agents_pkey" ON public."Agents" USING btree (id);

CREATE UNIQUE INDEX "Memories_pkey" ON public."Memories" USING btree (id);

CREATE UNIQUE INDEX "Plans_pkey" ON public."Plans" USING btree (id);

alter table "public"."Agents" add constraint "Agents_pkey" PRIMARY KEY using index "Agents_pkey";

alter table "public"."Memories" add constraint "Memories_pkey" PRIMARY KEY using index "Memories_pkey";

alter table "public"."Plans" add constraint "Plans_pkey" PRIMARY KEY using index "Plans_pkey";


