name: Test Setup Script

on:
  push:
    branches:
      - joshua/dev-59-setup-script
  pull_request:
    branches:
      - main

jobs:
  test_script:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.11]
        include:
          - os: macos-latest
            arch: arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Set up Homebrew
        if: contains(matrix.os, 'macos') || contains(matrix.os, 'ubuntu')
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH

      - name: Set up Homebrew on ARM Mac
        if: matrix.arch == 'arm64'
        run: |
          arch -arm64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          echo "/opt/homebrew/bin" >> $GITHUB_PATH

      - name: Run setup.py
        run: |
          python setup.py