name: Test Setup Script

on:
  push:
    branches:
      - joshua/dev-59-setup-script
  pull_request:
    branches:
      - main

env:
  CI: true

jobs:
  test_script:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Set up Homebrew
        if: contains(matrix.os, 'macos') || contains(matrix.os, 'ubuntu')
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH

      - name: Run setup.py
        run: |
          python setup.py